// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uukduoqhlwifywozsaqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1a2R1b3FobHdpZnl3b3pzYXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjAxNTAsImV4cCI6MjA3MDAzNjE1MH0.uBMRovHgFxSFUw5sD8pUmVGq5IHBI9nhIkUkZ8QZpeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});